AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - !ruby/regexp /old_and_unused\.rb$/

Style/ClassAndModuleChildren:
  Enabled: false


Style/Documentation:
  Enabled: false


Style/StringLiterals:
  Enabled: false

Style/ExtraSpacing:
  Enabled: false

Metrics/LineLength:
  Max: 200